import "./globals.css";
import { Inter } from "next/font/google";
import SessionProvider from "../components/SessionProvider";
// import RecoilRoot from "recoil";
// import { RecoilRoot } from "recoil";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Instagramm 1.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 h-screen">
        {/* session  */}
        <SessionProvider>
          {/* <RecoilRoot>{children}</RecoilRoot> */}
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
