import "./globals.css";
import { Inter } from "next/font/google";
import SessionProvider from "../components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Instagramm 1.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 h-screen">
        {/* session  */}
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
